### ISSUE TITLE
Domestic prices 3.0 API endpoint is giving 500 Internal Server Error when dimension values are greater than 0 

### ISSUE THREAD

**Issue by ShaharyarT** [USPS/api-examples#19]
I am using [Performs a search for base price and extraServices using the submitted rate ingredients. If itemValue is not included the response will not include insurance, registered mail, and collect on delivery extra services. If the extraService array is not specified then all eligible extra services will be included.](https://developer.usps.com/api/73)

**To reproduce**
1. Send the following request to the (https://api-cat.usps.com/prices/v3/total-rates/search)
`{
  "originZIPCode": "32796",
  "destinationZIPCode": "92656",
  "weight": 5,
  "length": 6,
  "width": 6,
  "height": 6,
  "priceType": "RETAIL",
  "mailingDate": "2023-09-27"
}`

2. See error
`There was an internal server error.`

**Expected behavior**
It should return all available services based on the given dimensions

**Comment by John-0927** [comment]
I have exactly the same issue.

**Comment by John-0927** [comment]
Still not working when dimension values are greater than 0

**Comment by kabutotx** [comment]
I'm not having any problems with my test domestic prices v3. Is it the Domestric Prices V3 API?
The first message doesn't seem to have a valid URL, that I see.

**Comment by kabutotx** [comment]
Ah, I see. I didn't add that function yet.

**Comment by kabutotx** [comment]
Added function and used sample data in 1st message and worked fine for me.

**Comment by kabutotx** [comment]
Take that back, Forgot to change mailingDate. I get errors with the sample mailingDate. I have "2023-10-11" on my first try and that worked.

**Comment by ShaharyarT** [comment]
This is now working fine. Closing the issue.
