### ISSUE TITLE
List of all fields returned.

### ISSUE THREAD

**Issue by madedigba** [USPS/api-examples#4]
Can a list of all fields that can be returned by each API be provided? Currently concerned  by the Single Track API and more specifically fields indicating expected/predicted delivery date.

**Comment by charlenebedford-usps** [comment]
Hello, 
I have added this request to the application teams internal tracker to create an interface document and upload it here, next to the postman collections. thank you

**Comment by stevenfdearborn** [comment]
The USPS Developer Portal contains all of the API documentation.  Please go to developer.usps.com for all this information.
