### ISSUE TITLE
Where can we find sample Tracking IDs in the testing environment?

### ISSUE THREAD

**Issue by melissarh57** [USPS/api-examples#5]
I'm working on connecting to the tracking API in the testing environment in order to get tracking info when sending in the tracking id as a URL parameter. However, I don't see any place to create fake shipments in the USPS sandbox environment to test out different tracking scenario responses. Nor do I see anything in the documentation. Does anyone have any guidance on this? 

On another note, I noticed the developer-cat.usps.com website went down twice in the last 2 hours. Is the developer portal and cat developer portal fully supported by USPS at this time, or still unreliable and in early stages? I'm not seeing good documentation on this and would love some clarity!

**Comment by charlenebedford-usps** [comment]
Hello Melissa. Yes there is still some work to create a label in CAT and then be able to track that label. I have added this request to our internal tracker and will provide an update as soon as possible. Thank you for your time and comment. In the interim i can get tracking numbers for cat that you can use. They are generally valid for 45 days. Let me know. Thanks
